//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class ApiException : ApplicationException {
        
        private ApiError[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", Order=0)]
        public ApiError[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DatabaseError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringLengthError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SizeLimitError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequiredError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RejectedError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReadOnlyError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RateExceededError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RangeError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QuotaCheckError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatorError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperationAccessDenied))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NullError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotEmptyError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternalApiError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DistinctError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientTermsError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthorizationError))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationError))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public abstract partial class ApiError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldPathField;
        
        private string triggerField;
        
        private string errorStringField;
        
        private string apiErrorTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fieldPath {
            get {
                return this.fieldPathField;
            }
            set {
                this.fieldPathField = value;
                this.RaisePropertyChanged("fieldPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string trigger {
            get {
                return this.triggerField;
            }
            set {
                this.triggerField = value;
                this.RaisePropertyChanged("trigger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string errorString {
            get {
                return this.errorStringField;
            }
            set {
                this.errorStringField = value;
                this.RaisePropertyChanged("errorString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApiError.Type", Order=3)]
        public string ApiErrorType {
            get {
                return this.apiErrorTypeField;
            }
            set {
                this.apiErrorTypeField = value;
                this.RaisePropertyChanged("ApiErrorType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApiException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class ApplicationException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string applicationExceptionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicationException.Type", Order=1)]
        public string ApplicationExceptionType {
            get {
                return this.applicationExceptionTypeField;
            }
            set {
                this.applicationExceptionTypeField = value;
                this.RaisePropertyChanged("ApplicationExceptionType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private string currencyCodeField;
        
        private string dateTimeZoneField;
        
        private string descriptiveNameField;
        
        private string companyNameField;
        
        private bool canManageClientsField;
        
        private bool canManageClientsFieldSpecified;
        
        private bool testAccountField;
        
        private bool testAccountFieldSpecified;
        
        private bool autoTaggingEnabledField;
        
        private bool autoTaggingEnabledFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("customerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerIdSpecified {
            get {
                return this.customerIdFieldSpecified;
            }
            set {
                this.customerIdFieldSpecified = value;
                this.RaisePropertyChanged("customerIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dateTimeZone {
            get {
                return this.dateTimeZoneField;
            }
            set {
                this.dateTimeZoneField = value;
                this.RaisePropertyChanged("dateTimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descriptiveName {
            get {
                return this.descriptiveNameField;
            }
            set {
                this.descriptiveNameField = value;
                this.RaisePropertyChanged("descriptiveName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("companyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool canManageClients {
            get {
                return this.canManageClientsField;
            }
            set {
                this.canManageClientsField = value;
                this.RaisePropertyChanged("canManageClients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canManageClientsSpecified {
            get {
                return this.canManageClientsFieldSpecified;
            }
            set {
                this.canManageClientsFieldSpecified = value;
                this.RaisePropertyChanged("canManageClientsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool testAccount {
            get {
                return this.testAccountField;
            }
            set {
                this.testAccountField = value;
                this.RaisePropertyChanged("testAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testAccountSpecified {
            get {
                return this.testAccountFieldSpecified;
            }
            set {
                this.testAccountFieldSpecified = value;
                this.RaisePropertyChanged("testAccountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool autoTaggingEnabled {
            get {
                return this.autoTaggingEnabledField;
            }
            set {
                this.autoTaggingEnabledField = value;
                this.RaisePropertyChanged("autoTaggingEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoTaggingEnabledSpecified {
            get {
                return this.autoTaggingEnabledFieldSpecified;
            }
            set {
                this.autoTaggingEnabledFieldSpecified = value;
                this.RaisePropertyChanged("autoTaggingEnabledSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class DatabaseError : ApiError {
        
        private DatabaseErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DatabaseErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DatabaseError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum DatabaseErrorReason {
        
        /// <remarks/>
        CONCURRENT_MODIFICATION,
        
        /// <remarks/>
        PERMISSION_DENIED,
        
        /// <remarks/>
        CAMPAIGN_PRODUCT_NOT_SUPPORTED,
        
        /// <remarks/>
        DUPLICATE_KEY,
        
        /// <remarks/>
        DATABASE_ERROR,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class StringLengthError : ApiError {
        
        private StringLengthErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StringLengthErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="StringLengthError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum StringLengthErrorReason {
        
        /// <remarks/>
        TOO_SHORT,
        
        /// <remarks/>
        TOO_LONG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class SizeLimitError : ApiError {
        
        private SizeLimitErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SizeLimitErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SizeLimitError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum SizeLimitErrorReason {
        
        /// <remarks/>
        REQUEST_SIZE_LIMIT_EXCEEDED,
        
        /// <remarks/>
        RESPONSE_SIZE_LIMIT_EXCEEDED,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class RequiredError : ApiError {
        
        private RequiredErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequiredErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequiredError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum RequiredErrorReason {
        
        /// <remarks/>
        REQUIRED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class RequestError : ApiError {
        
        private RequestErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RequestError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum RequestErrorReason {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        INVALID_INPUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class RejectedError : ApiError {
        
        private RejectedErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RejectedErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RejectedError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum RejectedErrorReason {
        
        /// <remarks/>
        UNKNOWN_VALUE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class ReadOnlyError : ApiError {
        
        private ReadOnlyErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReadOnlyErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ReadOnlyError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum ReadOnlyErrorReason {
        
        /// <remarks/>
        READ_ONLY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class RateExceededError : ApiError {
        
        private RateExceededErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        private string rateNameField;
        
        private string rateScopeField;
        
        private int retryAfterSecondsField;
        
        private bool retryAfterSecondsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RateExceededErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string rateName {
            get {
                return this.rateNameField;
            }
            set {
                this.rateNameField = value;
                this.RaisePropertyChanged("rateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string rateScope {
            get {
                return this.rateScopeField;
            }
            set {
                this.rateScopeField = value;
                this.RaisePropertyChanged("rateScope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int retryAfterSeconds {
            get {
                return this.retryAfterSecondsField;
            }
            set {
                this.retryAfterSecondsField = value;
                this.RaisePropertyChanged("retryAfterSeconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retryAfterSecondsSpecified {
            get {
                return this.retryAfterSecondsFieldSpecified;
            }
            set {
                this.retryAfterSecondsFieldSpecified = value;
                this.RaisePropertyChanged("retryAfterSecondsSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RateExceededError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum RateExceededErrorReason {
        
        /// <remarks/>
        RATE_EXCEEDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class RangeError : ApiError {
        
        private RangeErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RangeErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RangeError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum RangeErrorReason {
        
        /// <remarks/>
        TOO_LOW,
        
        /// <remarks/>
        TOO_HIGH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class QuotaCheckError : ApiError {
        
        private QuotaCheckErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QuotaCheckErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="QuotaCheckError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum QuotaCheckErrorReason {
        
        /// <remarks/>
        INVALID_TOKEN_HEADER,
        
        /// <remarks/>
        ACCOUNT_DELINQUENT,
        
        /// <remarks/>
        ACCOUNT_INACCESSIBLE,
        
        /// <remarks/>
        ACCOUNT_INACTIVE,
        
        /// <remarks/>
        INCOMPLETE_SIGNUP,
        
        /// <remarks/>
        INCOMPLETE_SIGNUP_LATEST_ADWORDS_API_TNC_NOT_AGREED,
        
        /// <remarks/>
        INCOMPLETE_SIGNUP_NO_BILLING_INFO,
        
        /// <remarks/>
        INCOMPLETE_SIGNUP_USER_INFO_MISSING,
        
        /// <remarks/>
        INCOMPLETE_SIGNUP_USER_INFO_PENDING,
        
        /// <remarks/>
        INCOMPLETE_SIGNUP_USER_INFO_REJECTED,
        
        /// <remarks/>
        MONTHLY_BUDGET_REACHED,
        
        /// <remarks/>
        QUOTA_EXCEEDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class OperatorError : ApiError {
        
        private OperatorErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperatorErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OperatorError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum OperatorErrorReason {
        
        /// <remarks/>
        OPERATOR_NOT_SUPPORTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class OperationAccessDenied : ApiError {
        
        private OperationAccessDeniedReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public OperationAccessDeniedReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OperationAccessDenied.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum OperationAccessDeniedReason {
        
        /// <remarks/>
        ACTION_NOT_PERMITTED,
        
        /// <remarks/>
        ADD_OPERATION_NOT_PERMITTED,
        
        /// <remarks/>
        REMOVE_OPERATION_NOT_PERMITTED,
        
        /// <remarks/>
        SET_OPERATION_NOT_PERMITTED,
        
        /// <remarks/>
        MUTATE_ACTION_NOT_PERMITTED_FOR_CLIENT,
        
        /// <remarks/>
        OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class NullError : ApiError {
        
        private NullErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NullErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NullError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum NullErrorReason {
        
        /// <remarks/>
        NULL_CONTENT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class NotEmptyError : ApiError {
        
        private NotEmptyErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotEmptyErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="NotEmptyError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum NotEmptyErrorReason {
        
        /// <remarks/>
        EMPTY_LIST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class InternalApiError : ApiError {
        
        private InternalApiErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InternalApiErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="InternalApiError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum InternalApiErrorReason {
        
        /// <remarks/>
        UNEXPECTED_INTERNAL_API_ERROR,
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        DOWNTIME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class IdError : ApiError {
        
        private IdErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="IdError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum IdErrorReason {
        
        /// <remarks/>
        NOT_FOUND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class DistinctError : ApiError {
        
        private DistinctErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DistinctErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DistinctError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum DistinctErrorReason {
        
        /// <remarks/>
        DUPLICATE_ELEMENT,
        
        /// <remarks/>
        DUPLICATE_TYPE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class ClientTermsError : ApiError {
        
        private ClientTermsErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClientTermsErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ClientTermsError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum ClientTermsErrorReason {
        
        /// <remarks/>
        INCOMPLETE_SIGNUP_CURRENT_ADWORDS_TNC_NOT_AGREED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class AuthorizationError : ApiError {
        
        private AuthorizationErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthorizationErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="AuthorizationError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum AuthorizationErrorReason {
        
        /// <remarks/>
        UNABLE_TO_AUTHORIZE,
        
        /// <remarks/>
        NO_ADWORDS_ACCOUNT_FOR_CUSTOMER,
        
        /// <remarks/>
        USER_PERMISSION_DENIED,
        
        /// <remarks/>
        EFFECTIVE_USER_PERMISSION_DENIED,
        
        /// <remarks/>
        USER_HAS_READONLY_PERMISSION,
        
        /// <remarks/>
        NO_CUSTOMER_FOUND,
        
        /// <remarks/>
        SERVICE_ACCESS_DENIED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class AuthenticationError : ApiError {
        
        private AuthenticationErrorReason reasonField;
        
        private bool reasonFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthenticationErrorReason reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reasonSpecified {
            get {
                return this.reasonFieldSpecified;
            }
            set {
                this.reasonFieldSpecified = value;
                this.RaisePropertyChanged("reasonSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="AuthenticationError.Reason", Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public enum AuthenticationErrorReason {
        
        /// <remarks/>
        AUTHENTICATION_FAILED,
        
        /// <remarks/>
        CLIENT_CUSTOMER_ID_IS_REQUIRED,
        
        /// <remarks/>
        CLIENT_EMAIL_REQUIRED,
        
        /// <remarks/>
        CLIENT_CUSTOMER_ID_INVALID,
        
        /// <remarks/>
        CLIENT_EMAIL_INVALID,
        
        /// <remarks/>
        CLIENT_EMAIL_FAILED_TO_AUTHENTICATE,
        
        /// <remarks/>
        CUSTOMER_NOT_FOUND,
        
        /// <remarks/>
        GOOGLE_ACCOUNT_DELETED,
        
        /// <remarks/>
        GOOGLE_ACCOUNT_COOKIE_INVALID,
        
        /// <remarks/>
        FAILED_TO_AUTHENTICATE_GOOGLE_ACCOUNT,
        
        /// <remarks/>
        GOOGLE_ACCOUNT_USER_AND_ADS_USER_MISMATCH,
        
        /// <remarks/>
        LOGIN_COOKIE_REQUIRED,
        
        /// <remarks/>
        NOT_ADS_USER,
        
        /// <remarks/>
        OAUTH_TOKEN_INVALID,
        
        /// <remarks/>
        OAUTH_TOKEN_EXPIRED,
        
        /// <remarks/>
        OAUTH_TOKEN_DISABLED,
        
        /// <remarks/>
        OAUTH_TOKEN_REVOKED,
        
        /// <remarks/>
        OAUTH_TOKEN_HEADER_INVALID,
        
        /// <remarks/>
        LOGIN_COOKIE_INVALID,
        
        /// <remarks/>
        FAILED_TO_RETRIEVE_LOGIN_COOKIE,
        
        /// <remarks/>
        USER_ID_INVALID,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402", ConfigurationName="ServiceReference1.CustomerServiceInterface")]
    public interface CustomerServiceInterface {
        
        // CODEGEN: Generating message contract since message getRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebService.ServiceReference1.ApiException), Action="", Name="ApiExceptionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationException))]
        WebService.ServiceReference1.getResponse get(WebService.ServiceReference1.getRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.getResponse> getAsync(WebService.ServiceReference1.getRequest request);
        
        // CODEGEN: Generating message contract since message mutateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebService.ServiceReference1.ApiException), Action="", Name="ApiExceptionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApplicationException))]
        WebService.ServiceReference1.mutateResponse mutate(WebService.ServiceReference1.mutateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ServiceReference1.mutateResponse> mutateAsync(WebService.ServiceReference1.mutateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class SoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientCustomerIdField;
        
        private string developerTokenField;
        
        private string userAgentField;
        
        private bool validateOnlyField;
        
        private bool validateOnlyFieldSpecified;
        
        private bool partialFailureField;
        
        private bool partialFailureFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientCustomerId {
            get {
                return this.clientCustomerIdField;
            }
            set {
                this.clientCustomerIdField = value;
                this.RaisePropertyChanged("clientCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string developerToken {
            get {
                return this.developerTokenField;
            }
            set {
                this.developerTokenField = value;
                this.RaisePropertyChanged("developerToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("userAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool validateOnly {
            get {
                return this.validateOnlyField;
            }
            set {
                this.validateOnlyField = value;
                this.RaisePropertyChanged("validateOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validateOnlySpecified {
            get {
                return this.validateOnlyFieldSpecified;
            }
            set {
                this.validateOnlyFieldSpecified = value;
                this.RaisePropertyChanged("validateOnlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool partialFailure {
            get {
                return this.partialFailureField;
            }
            set {
                this.partialFailureField = value;
                this.RaisePropertyChanged("partialFailure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partialFailureSpecified {
            get {
                return this.partialFailureFieldSpecified;
            }
            set {
                this.partialFailureFieldSpecified = value;
                this.RaisePropertyChanged("partialFailureSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://adwords.google.com/api/adwords/cm/v201402")]
    public partial class SoapResponseHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string serviceNameField;
        
        private string methodNameField;
        
        private long operationsField;
        
        private bool operationsFieldSpecified;
        
        private long responseTimeField;
        
        private bool responseTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
                this.RaisePropertyChanged("methodName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long operations {
            get {
                return this.operationsField;
            }
            set {
                this.operationsField = value;
                this.RaisePropertyChanged("operations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool operationsSpecified {
            get {
                return this.operationsFieldSpecified;
            }
            set {
                this.operationsFieldSpecified = value;
                this.RaisePropertyChanged("operationsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long responseTime {
            get {
                return this.responseTimeField;
            }
            set {
                this.responseTimeField = value;
                this.RaisePropertyChanged("responseTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseTimeSpecified {
            get {
                return this.responseTimeFieldSpecified;
            }
            set {
                this.responseTimeFieldSpecified = value;
                this.RaisePropertyChanged("responseTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="https://adwords.google.com/api/adwords/mcm/v201402", IsWrapped=true)]
    public partial class getRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402")]
        public WebService.ServiceReference1.SoapHeader RequestHeader;
        
        public getRequest() {
        }
        
        public getRequest(WebService.ServiceReference1.SoapHeader RequestHeader) {
            this.RequestHeader = RequestHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="https://adwords.google.com/api/adwords/mcm/v201402", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402")]
        public WebService.ServiceReference1.SoapResponseHeader ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402", Order=0)]
        public WebService.ServiceReference1.Customer rval;
        
        public getResponse() {
        }
        
        public getResponse(WebService.ServiceReference1.SoapResponseHeader ResponseHeader, WebService.ServiceReference1.Customer rval) {
            this.ResponseHeader = ResponseHeader;
            this.rval = rval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mutate", WrapperNamespace="https://adwords.google.com/api/adwords/mcm/v201402", IsWrapped=true)]
    public partial class mutateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402")]
        public WebService.ServiceReference1.SoapHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402", Order=0)]
        public WebService.ServiceReference1.Customer customer;
        
        public mutateRequest() {
        }
        
        public mutateRequest(WebService.ServiceReference1.SoapHeader RequestHeader, WebService.ServiceReference1.Customer customer) {
            this.RequestHeader = RequestHeader;
            this.customer = customer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mutateResponse", WrapperNamespace="https://adwords.google.com/api/adwords/mcm/v201402", IsWrapped=true)]
    public partial class mutateResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402")]
        public WebService.ServiceReference1.SoapResponseHeader ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://adwords.google.com/api/adwords/mcm/v201402", Order=0)]
        public WebService.ServiceReference1.Customer rval;
        
        public mutateResponse() {
        }
        
        public mutateResponse(WebService.ServiceReference1.SoapResponseHeader ResponseHeader, WebService.ServiceReference1.Customer rval) {
            this.ResponseHeader = ResponseHeader;
            this.rval = rval;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceInterfaceChannel : WebService.ServiceReference1.CustomerServiceInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceInterfaceClient : System.ServiceModel.ClientBase<WebService.ServiceReference1.CustomerServiceInterface>, WebService.ServiceReference1.CustomerServiceInterface {
        
        public CustomerServiceInterfaceClient() {
        }
        
        public CustomerServiceInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.getResponse WebService.ServiceReference1.CustomerServiceInterface.get(WebService.ServiceReference1.getRequest request) {
            return base.Channel.get(request);
        }
        
        public WebService.ServiceReference1.SoapResponseHeader get(WebService.ServiceReference1.SoapHeader RequestHeader, out WebService.ServiceReference1.Customer rval) {
            WebService.ServiceReference1.getRequest inValue = new WebService.ServiceReference1.getRequest();
            inValue.RequestHeader = RequestHeader;
            WebService.ServiceReference1.getResponse retVal = ((WebService.ServiceReference1.CustomerServiceInterface)(this)).get(inValue);
            rval = retVal.rval;
            return retVal.ResponseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.getResponse> WebService.ServiceReference1.CustomerServiceInterface.getAsync(WebService.ServiceReference1.getRequest request) {
            return base.Channel.getAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.getResponse> getAsync(WebService.ServiceReference1.SoapHeader RequestHeader) {
            WebService.ServiceReference1.getRequest inValue = new WebService.ServiceReference1.getRequest();
            inValue.RequestHeader = RequestHeader;
            return ((WebService.ServiceReference1.CustomerServiceInterface)(this)).getAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.ServiceReference1.mutateResponse WebService.ServiceReference1.CustomerServiceInterface.mutate(WebService.ServiceReference1.mutateRequest request) {
            return base.Channel.mutate(request);
        }
        
        public WebService.ServiceReference1.SoapResponseHeader mutate(WebService.ServiceReference1.SoapHeader RequestHeader, WebService.ServiceReference1.Customer customer, out WebService.ServiceReference1.Customer rval) {
            WebService.ServiceReference1.mutateRequest inValue = new WebService.ServiceReference1.mutateRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.customer = customer;
            WebService.ServiceReference1.mutateResponse retVal = ((WebService.ServiceReference1.CustomerServiceInterface)(this)).mutate(inValue);
            rval = retVal.rval;
            return retVal.ResponseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.ServiceReference1.mutateResponse> WebService.ServiceReference1.CustomerServiceInterface.mutateAsync(WebService.ServiceReference1.mutateRequest request) {
            return base.Channel.mutateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ServiceReference1.mutateResponse> mutateAsync(WebService.ServiceReference1.SoapHeader RequestHeader, WebService.ServiceReference1.Customer customer) {
            WebService.ServiceReference1.mutateRequest inValue = new WebService.ServiceReference1.mutateRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.customer = customer;
            return ((WebService.ServiceReference1.CustomerServiceInterface)(this)).mutateAsync(inValue);
        }
    }
}
